### ISSUE TITLE
✨ MVP Update Part 2

### ISSUE THREAD

**Issue by 0xAndrewBlack** [0xAndrewBlack/issue-bot#38]
New fields

- [x] Priorities updated to (Low, Medium, High, Critical)
- [ ] Story (with Drop and story options) #42

Updates
- [ ] Put thread link in GitHub issue. #42
- [x] If an issue has a critical priority put a `🚩` instead of the normal statuses.
- [ ] Scrape GitHub custom fields to dynamically update other fields on the go. #42
- [ ] GitHub side sync 👀 #42 

Fixes
- [x] Status anomalies
- [x] Weird issue closing sometimes
- [x] Improve logging.
